[package]
name = "happy_face"
version = "0.1.0"
authors = ["jacob"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
message-io = "0.8.1"
serde = "1.0.123"
serde_json = "1.0.63"
